/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.horn.michael;

import java.text.NumberFormat;

/**
 *
 * @author Mike
 */
public class AddModifyPartForm extends javax.swing.JFrame {

    private Part thisPart;
    private MainScreen parent;
    private Inventory inventory;

    public MainScreen getParent() {
        return parent;
    }

    public void setParent(MainScreen parent) {
        this.parent = parent;
    }

    public Inventory getInventory() {
        return inventory;
    }

    public void setInventory(Inventory inventory) {
        this.inventory = inventory;
    }
    

    public Part getThisPart() {
        return thisPart;
    }

    public void setThisPart(Part thisPart) {
        this.thisPart = thisPart;
        if(this.thisPart != null)
        {
            this.titleLabel.setText("Modify Part");
            this.partIDTB.setText(   Integer.toString(this.thisPart.getPartID()));
            this.partNameTB.setText(this.thisPart.getName());
            this.partPriceTB.setText(NumberFormat.getCurrencyInstance().format(this.thisPart.getPrice()));
            this.partInvTB.setText(Integer.toString(this.thisPart.getInstock()));
            this.partMaxSpin.setValue(this.thisPart.getMax());
            this.partMinSpin.setValue(this.thisPart.getMin());
            
            if(this.thisPart instanceof InHouse)
            {
                InHouse ih = (InHouse) thisPart;
                this.partMachineIDTB.setText(Integer.toString(ih.getInstock()));
            }else{
                Outsourced os = (Outsourced) thisPart;
                this.partCompanyNameTB.setText(os.getCompanyName());
            }
        }else{
            this.titleLabel.setText("Add Part");
        }
        
    }
    
    /**
     * Creates new form AddPartForm
     */
    public AddModifyPartForm() {
        initComponents();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        titleLabel = new javax.swing.JLabel();
        inHouseRadioBtn = new javax.swing.JRadioButton();
        outsourcedRadioBtn = new javax.swing.JRadioButton();
        cancelBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        partIDTB = new javax.swing.JTextField();
        partNameTB = new javax.swing.JTextField();
        partInvTB = new javax.swing.JTextField();
        partPriceTB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        partTypeLabel = new javax.swing.JLabel();
        partCompanyNameTB = new javax.swing.JTextField();
        partMaxSpin = new javax.swing.JSpinner();
        partMinSpin = new javax.swing.JSpinner();
        partTypeLabel1 = new javax.swing.JLabel();
        partMachineIDTB = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(330, 330));
        setResizable(false);
        setSize(new java.awt.Dimension(330, 330));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 153, 204));
        titleLabel.setText("Add Part");

        buttonGroup2.add(inHouseRadioBtn);
        inHouseRadioBtn.setSelected(true);
        inHouseRadioBtn.setToolTipText("");
        inHouseRadioBtn.setLabel("In-House");
        inHouseRadioBtn.setName(""); // NOI18N
        inHouseRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inHouseRadioBtnActionPerformed(evt);
            }
        });

        buttonGroup2.add(outsourcedRadioBtn);
        outsourcedRadioBtn.setText("Outsourced");
        outsourcedRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outsourcedRadioBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        jLabel3.setText("Name");

        jLabel4.setText("Inv");

        jLabel5.setText("Price/Cost");

        jLabel6.setText("Max");

        partPriceTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partPriceTBActionPerformed(evt);
            }
        });

        jLabel7.setText("Min");

        partTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        partTypeLabel.setText("Company Name");
        partTypeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        partTypeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        partTypeLabel1.setText("Machine ID");
        partTypeLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(titleLabel)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(partTypeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(partTypeLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inHouseRadioBtn)
                        .addGap(1, 1, 1)
                        .addComponent(outsourcedRadioBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(partMachineIDTB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(partIDTB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(partNameTB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(partInvTB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(partPriceTB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(partMaxSpin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(partMinSpin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(partCompanyNameTB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelBtn)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inHouseRadioBtn)
                            .addComponent(outsourcedRadioBtn))))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partIDTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partNameTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partInvTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partPriceTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partMaxSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partMinSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTypeLabel)
                    .addComponent(partCompanyNameTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partMachineIDTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partTypeLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inHouseRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inHouseRadioBtnActionPerformed
        // TODO add your handling code here:
        updatePartType();
    }//GEN-LAST:event_inHouseRadioBtnActionPerformed

    private void outsourcedRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outsourcedRadioBtnActionPerformed
        updatePartType();
    }//GEN-LAST:event_outsourcedRadioBtnActionPerformed

    private void partPriceTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partPriceTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partPriceTBActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        initPartType();
    }//GEN-LAST:event_formWindowOpened

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        this.getParent().onDataUpdate();
    }//GEN-LAST:event_saveBtnActionPerformed

    void updatePartType()
    { 
        if(this.inHouseRadioBtn.isSelected())
        {
            this.partTypeLabel.setVisible(false);
            this.partTypeLabel1.setVisible(true);
        
            this.partCompanyNameTB.setVisible(false);
            this.partMachineIDTB.setVisible(true);
            
        }else{
            this.partTypeLabel.setVisible(true);
            this.partTypeLabel1.setVisible(false);
            
            this.partCompanyNameTB.setVisible(true);
            this.partMachineIDTB.setVisible(false);
        }
    }
    
    void initPartType()
    {
        if(this.thisPart instanceof InHouse)
        {
            this.inHouseRadioBtn.doClick();
           
        }else{
            this.outsourcedRadioBtn.doClick();
            
        }
        
        
    }
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddModifyPartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddModifyPartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddModifyPartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddModifyPartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddModifyPartForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JRadioButton inHouseRadioBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton outsourcedRadioBtn;
    private javax.swing.JTextField partCompanyNameTB;
    private javax.swing.JTextField partIDTB;
    private javax.swing.JTextField partInvTB;
    private javax.swing.JTextField partMachineIDTB;
    private javax.swing.JSpinner partMaxSpin;
    private javax.swing.JSpinner partMinSpin;
    private javax.swing.JTextField partNameTB;
    private javax.swing.JTextField partPriceTB;
    private javax.swing.JLabel partTypeLabel;
    private javax.swing.JLabel partTypeLabel1;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
