/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.horn.michael;

import java.text.NumberFormat;
import java.util.List;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Mike
 */
public class MainScreen extends javax.swing.JFrame {

  
    private Inventory inventory = new Inventory();
    
    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
       initComponents();
       initInventory();
       initPartsTable();
       initProductsTable();
        
    }

    private void initParts()
    {
        inventory.addPart( new InHouse("IH - Part 1", 5.00, 5,1,5, 200) );
        inventory.addPart( new InHouse("IH - Part 2", 5.00, 5,1,5, 200) );
        inventory.addPart( new InHouse("IH - Part 3", 5.00, 5,1,5, 200) );
        inventory.addPart( new InHouse("IH - Part 4", 5.00, 5,1,5, 200) );
        
        inventory.addPart( new Outsourced("OS - Part 1", 5.00, 5,1,5, "ACME") );
        inventory.addPart( new Outsourced("OS - Part 2", 5.00, 5,1,5, "ACME") );
        inventory.addPart( new Outsourced("OS - Part 3", 5.00, 5,1,5, "ACME") );
        inventory.addPart( new Outsourced("OS - Part 4", 5.00, 5,1,5, "ACME") );
        
    }
    
    private void initProducts()
    {
        inventory.addProduct( new Product("Product 1", 5.00, 5, 1, 5));
        inventory.addProduct( new Product("Product 2", 10.00, 10, 1, 5));
    }
    
    private void initInventory()
    {
        initParts();
        initProducts();
        
       
        
    }
    
    private void  initProductsTable()
    {
        
        ArrayList<Product> prods =  inventory.getProducts();
     
        List<Object[]> list = new ArrayList<Object[]>();
        for (int i = 0; i <prods.size(); i++) {
            list.add(new Object[] { 
                                  prods.get(i).getProductID(),
                                  prods.get(i).getName(),
                                  prods.get(i).getInstock(),
                                  NumberFormat.getCurrencyInstance().format(prods.get(i).getPrice())
                              });

        }
       
        
        prodTable.setModel(new DefaultTableModel(list.toArray(new Object[][] {}), 
                        new String[] {"Product ID", "Product Name", "Inventory Level", "Price/Cost per Unit"}));
    }
    
    
    private void initPartsTable()
    {
          
        ArrayList<Part> prods =  inventory.getParts();
     
        List<Object[]> list = new ArrayList<Object[]>();
        for (int i = 0; i <prods.size(); i++) {
            list.add(new Object[] { 
                                  prods.get(i).getPartID(),
                                  prods.get(i).getName(),
                                  prods.get(i).getInstock(),
                                  NumberFormat.getCurrencyInstance().format(prods.get(i).getPrice())
                              });

        }
       
        
        partsTable.setModel(new DefaultTableModel(list.toArray(new Object[][] {}), 
                        new String[] {"Part ID", "Part Name", "Inventory Level", "Price/Cost per Unit"}));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CloseBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prodTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        searchProdBtn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        addProdBtn = new javax.swing.JButton();
        modifyProdBtn = new javax.swing.JButton();
        deleteProdBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        partsTable = new javax.swing.JTable();
        partsSearchBtn = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        addPartBtn = new javax.swing.JButton();
        modifyPartBtn = new javax.swing.JButton();
        deletePartBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CloseBtn.setText("Exit");
        CloseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CloseBtnMousePressed(evt);
            }
        });
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Inventory Management System");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        prodTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(prodTable);

        jLabel2.setText("Products");

        searchProdBtn.setText("Search");

        jTextField1.setText("ID or Name (whole or part)");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        addProdBtn.setText("Add");

        modifyProdBtn.setText("Modify");

        deleteProdBtn.setText("Delete");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(191, 191, 191)
                        .addComponent(searchProdBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(addProdBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modifyProdBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteProdBtn)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchProdBtn)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addProdBtn)
                    .addComponent(modifyProdBtn)
                    .addComponent(deleteProdBtn))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel3.setText("Parts");

        jScrollPane2.setViewportView(partsTable);

        partsSearchBtn.setText("Search");

        jTextField2.setText("ID or Name (whole or part)");
        jTextField2.setToolTipText("");

        addPartBtn.setText("Add");
        addPartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPartBtnActionPerformed(evt);
            }
        });

        modifyPartBtn.setText("Modify");
        modifyPartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyPartBtnActionPerformed(evt);
            }
        });

        deletePartBtn.setText("Delete");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(partsSearchBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(addPartBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modifyPartBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deletePartBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(partsSearchBtn)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPartBtn)
                    .addComponent(modifyPartBtn)
                    .addComponent(deletePartBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CloseBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CloseBtn)
                        .addGap(0, 12, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void CloseBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMousePressed
      System.exit(0);
      
    }//GEN-LAST:event_CloseBtnMousePressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void addPartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPartBtnActionPerformed
       
        AddModifyPartForm frame = new AddModifyPartForm();
        frame.setThisPart(null);
        frame.setParent(this);
        frame.setInventory(this.inventory);
        frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE );
        frame.pack();
       
        frame.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_addPartBtnActionPerformed

    private void modifyPartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyPartBtnActionPerformed
        // TODO add your handling code here:
       DefaultTableModel partsModel = (DefaultTableModel)partsTable.getModel();
       Vector vec = (Vector)partsModel.getDataVector().elementAt(partsTable.getSelectedRow());
       int partID = (int)vec.elementAt(0);
       Part targetPart = this.inventory.lookupPart(partID);
       

        
        AddModifyPartForm frame = new AddModifyPartForm();
        frame.setThisPart(targetPart);
        frame.setParent(this);
        frame.setInventory(this.inventory);
        frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE );
        frame.pack();
       
        frame.setVisible(true); 
        
    }//GEN-LAST:event_modifyPartBtnActionPerformed

    public void onDataUpdate()
    {
         int i =0;
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
                
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseBtn;
    private javax.swing.JButton addPartBtn;
    private javax.swing.JButton addProdBtn;
    private javax.swing.JButton deletePartBtn;
    private javax.swing.JButton deleteProdBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton modifyPartBtn;
    private javax.swing.JButton modifyProdBtn;
    private javax.swing.JButton partsSearchBtn;
    private javax.swing.JTable partsTable;
    private javax.swing.JTable prodTable;
    private javax.swing.JButton searchProdBtn;
    // End of variables declaration//GEN-END:variables
}
